### ISSUE TITLE
'ReferenceError: Items is not defined'

### ISSUE THREAD

**Issue by Laurisylva** [lirbank/meteor-accounts-merge#29]
I logged in with Google+ and 'signInWithGoogle'. It worked, the new user is created in MongoDB, then i was trying to connect Facebook, the both accounts merged correctly but this message apparead in the browser console :

```
errorClass {error: 500, reason: "Internal server error", details: undefined, message: "Internal server error [500]", errorType: "Meteor.Error"}details: undefinederror: 500errorType: "Meteor.Error"message: "Internal server error [500]"reason: "Internal server error"stack: (...)get stack: ()set stack: ()__proto__: Middle
debug.js:41 Exception in delivering result of invoking 'mergeAccounts': Error: [Facebook login failed]
    at http://localhost:3000/app/client/sections/log-sign/log-sign.component.js?b01a336678478d33515fb2f4fd7e3add0248bc6d:1:1615
    at http://localhost:3000/packages/mikael_accounts-merge.js?9b32002c64a0a7deecb1bd0e873e9ddb27a957b4:1:1130
    at null._callback (http://localhost:3000/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:999:22)
    at _.extend._maybeInvokeCallback (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:3500:12)
    at _.extend.dataVisible (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:3529:10)
    at http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:4365:7
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?46eaedbdeb6e71c82af1b16f51c7da4127d6f285:149:11)
    at _.extend._runAfterUpdateCallbacks (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:4364:7)
    at _.extend._livedata_data (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:4354:10)
```

I used this for showing these messages : 

``` javascript
Meteor.signInWithFacebook({}, function(err){
    if (err) {
        console.log(err);
        throw new Meteor.Error("Facebook login failed");
    }
}
```

So i checked on my server console and the error is : 

```
Exception while invoking method 'mergeAccounts' ReferenceError: Items is not defined
```

Details : 

```
I20160120-11:19:18.741(0)?     at livedata_server.js:708:19
I20160120-11:19:18.741(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js
:56:1)
I20160120-11:19:18.741(0)?     at livedata_server.js:706:40
I20160120-11:19:18.742(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js
:56:1)
I20160120-11:19:18.742(0)?     at livedata_server.js:704:46
I20160120-11:19:18.742(0)?     at tryCallTwo (/home/caudralys/.meteor/packages/promise/.0.5.1.1550ocw++o
s+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20160120-11:19:18.742(0)?     at doResolve (/home/caudralys/.meteor/packages/promise/.0.5.1.1550ocw++os
+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20160120-11:19:18.740(0)?     at Object.AccountsMerge.onMerge (server/accounts.js:33:1)
I20160120-11:19:18.740(0)?     at [object Object].Meteor.methods.mergeAccounts (packages/mikael_accounts
-merge/accounts-merge-server.js:66:1)
I20160120-11:19:18.741(0)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
```

And it is exactly the same with Twitter and Linkedin.

Do you know what happened ?
Thanks !

**Comment by Laurisylva** [comment]
I tried an other way for understanding : 
- i create an account with Facebook, it works, and i'm connecting to this account
- i disconnect, i create an other account with G+, then during this session, i connect/merge with Facebook
- the error appeares : data of Facebook goes into data of the second account G+ (it's normal) but i'm automatically reconnecting on the first account who is currently empty (because data is gone on the second account).

I think that is the error, how keeping the connection on the second account ? Or going to the first one but moving data from the second one to the first one ?

**Comment by Laurisylva** [comment]
Ok, this is my fault.
I used the example code from the documentation about "ON THE SERVER (optional)" and obviously, Items' collection doesn't exist on my DB.
